// Automatically generated by build process.

#ifndef BUILD_INFO_HH
#define BUILD_INFO_HH

#ifdef __MINGW64__
#define ASM_X86 0
#define ASM_X86 0
#define ASM_X86_32 0
#define ASM_X86_64 0
#else
#define ASM_X86 0
#define ASM_X86_32 0
#define ASM_X86_64 0
#endif
#define PLATFORM_DINGUX 0
#define PLATFORM_MAEMO5 0
#define PLATFORM_ANDROID 0
#define HAVE_16BPP 1
#define HAVE_32BPP 1
#define MIN_SCALE_FACTOR 1
#define MAX_SCALE_FACTOR 4

namespace openmsx {

static const bool OPENMSX_BIGENDIAN = false;
static const bool OPENMSX_UNALIGNED_MEMORY_ACCESS = false;
static const bool OPENMSX_SET_WINDOW_ICON = true;
static const char* const DATADIR = "/opt/retropie/emulators/openmsx//share";
static const char* const BUILD_FLAVOUR = "opt";
static const char* const TARGET_PLATFORM = "linux";

} // namespace openmsx

#endif // BUILD_INFO_HH
