// Automatically generated by build process.

#ifndef COMPONENTS_HH
#define COMPONENTS_HH

#define COMPONENT_CORE 1
#define COMPONENT_GL 1
#define COMPONENT_LASERDISC 1
#define COMPONENT_ALSAMIDI 1

namespace openmsx {

static const char* const BUILD_COMPONENTS = "ALSAMIDI CORE GL LASERDISC";

} // namespace openmsx

#endif // COMPONENTS_HH
