# Automatically generated by build system.
# Non-empty value means found, empty means not found.
HAVE_ALSA_H:=true
HAVE_ALSA_LIB:=true
ALSA_CFLAGS:=
ALSA_LDFLAGS:=-lasound
HAVE_GL_H:=true
HAVE_GL_LIB:=true
GL_CFLAGS:=
GL_LDFLAGS:=-lGL
HAVE_GLEW_H:=true
HAVE_GLEW_LIB:=true
GLEW_CFLAGS:=
GLEW_LDFLAGS:=-lGLEW
HAVE_OGG_H:=true
HAVE_OGG_LIB:=true
OGG_CFLAGS:=
OGG_LDFLAGS:=-logg
HAVE_PNG_H:=true
HAVE_PNG_LIB:=true
PNG_CFLAGS:=-I/usr/include/libpng12
PNG_LDFLAGS:=-lpng12
HAVE_SDL_H:=true
HAVE_SDL_LIB:=true
SDL_CFLAGS:=-I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT
SDL_LDFLAGS:=-L/usr/lib/arm-linux-gnueabihf -lSDL
HAVE_SDL_TTF_H:=true
HAVE_SDL_TTF_LIB:=true
SDL_TTF_CFLAGS:=-I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -I/usr/include/freetype2
SDL_TTF_LDFLAGS:=-lSDL_ttf -L/usr/lib/arm-linux-gnueabihf -lSDL
HAVE_TCL_H:=true
HAVE_TCL_LIB:=true
TCL_CFLAGS:=-I/usr/include/tcl8.5
TCL_LDFLAGS:=-L/usr/lib/arm-linux-gnueabihf -ltcl8.5
HAVE_THEORA_H:=true
HAVE_THEORA_LIB:=true
THEORA_CFLAGS:=
THEORA_LDFLAGS:=-ltheoradec
HAVE_VORBIS_H:=true
HAVE_VORBIS_LIB:=true
VORBIS_CFLAGS:=
VORBIS_LDFLAGS:=-lvorbis
HAVE_ZLIB_H:=true
HAVE_ZLIB_LIB:=true
ZLIB_CFLAGS:=
ZLIB_LDFLAGS:=-lz
